coffeenet:
  application-name: CoffeeNet Frontpage
  profile: development
  security:
    client:
      client-id: coffeeNetClient
      client-secret: coffeeNetClientSecret
  logging:
    console:
      enabled: true